apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: zurek
build:
  local:
    push: false
    useBuildkit: true
  artifacts:
    - image: backend
      context: backend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.*
            dest: .
          - src: test/**/*.*
            dest: .
          - src: libs/**/*.*
            dest: .
          - src: dist/**/*.*
            dest: .
          - src: package.json
            dest: .
          - src: package-lock.json
            dest: .
          - src: tsconfig.json
            dest: .
          - src: tsconfig.build.json
            dest: .
          - src: ormconfig.json
            dest: .
          - src: nest-cli.json
            dest: .
          - src: README.md
            dest: .
          - src: .eslintrc.js
            dest: .
          - src: .prettierrc
            dest: .
    - image: frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.*
            dest: .
          - src: test/**/*.*
            dest: .
          - src: libs/**/*.*
            dest: .
          - src: dist/**/*.*
            dest: .
          - src: public/**/*.*
            dest: .
          - src: .storybook/**/*.*
            dest: .
          - src: package.json
            dest: .
          - src: package-lock.json
            dest: .
          - src: babel.config.json
            dest: .
          - src: dev.webpack.config.js
            dest: .
          - src: tsconfig.json
            dest: .
          - src: tsconfig.build.json
            dest: .
          - src: README.md
            dest: .
          - src: .eslintrc.js
            dest: .
          - src: .prettierrc
            dest: .
deploy:
  kubectl:
    defaultNamespace: zurek
    flags:
      global: [--namespace=zurek]
    manifests:
      - ./kubernetes/namespaces.yaml
      - ./kubernetes/config-maps.yaml
      - ./kubernetes/secrets.yaml
      - ./kubernetes/service-accounts.yaml
      - ./kubernetes/services.yaml
      - ./kubernetes/storage-classes.yaml
      - ./kubernetes/volumes.yaml
      - ./kubernetes/ingress-classes.yaml
      - ./kubernetes/cluster-roles.yaml
      - ./kubernetes/cluster-role-bindings.yaml
      - ./kubernetes/custom-resources.yaml
      - ./kubernetes/deployment-postgres.yaml
      - ./kubernetes/deployment-redis.yaml
      - ./kubernetes/deployment-minio.yaml
      - ./kubernetes/deployment-backend.yaml
      - ./kubernetes/deployment-frontend.yaml
      # - ./kubernetes/deployment-pgadmin.yaml
      # - ./kubernetes/deployment-nginx.yaml
      # - ./kubernetes/ingresses.yaml
profiles:
  - name: development
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: dev.Dockerfile
      - op: replace
        path: /build/artifacts/1/docker/dockerfile
        value: dev.Dockerfile
      - op: replace
        path: /deploy/kubectl/manifests/14
        value: ./kubernetes/dev-deployment-backend.yaml
      - op: replace
        path: /deploy/kubectl/manifests/15
        value: ./kubernetes/dev-deployment-frontend.yaml
