apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: zurek
  name: frontend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: registry
      containers:
        - name: frontend
          image: frontend
          ports:
            - name: node
              containerPort: 8080
            - name: storybook
              containerPort: 6006
          volumeMounts:
            - mountPath: /home/node
              name: frontend
          env:
            - name: NODE_ENV
              value: development
            - name: STORYBOOK_PORT
              value: "6006"
            - name: HTTPS
              valueFrom:
                configMapKeyRef:
                  name: frontend
                  key: DEV_REACT_HTTPS
          resources:
            limits:
              cpu: 1500m
              memory: 2Gi
            requests:
              cpu: 1000m
              memory: 1Gi
          stdin: true
      serviceAccountName: frontend
      securityContext:
        runAsUser: 1000
      volumes:
        - name: frontend
          persistentVolumeClaim:
            claimName: frontend
