apiVersion: v1
kind: ConfigMap
metadata:
  namespace: zurek
  name: backend
data:
  POSTGRES_DB: backend
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: zurek
  name: minio
data:
  MINIO_ACCESS_KEY: minio
