apiVersion: v1
kind: ConfigMap
metadata:
  namespace: zurek
  name: postgres
  labels:
    app: postgres
data:
  POSTGRES_HOST: postgres.zurek
  POSTGRES_PORT: "5432"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: zurek
  name: minio
  labels:
    app: minio
data:
  MINIO_HOST: minio.zurek
  MINIO_ACCESS_KEY: minio
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: zurek
  name: backend
  labels:
    app: backend
data:
  DB_ENTITIES: dist/**/*.entity{.ts,.js}
  DB_SYNCHRONIZE: "false"
  NEST_DEBUG: "True"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: zurek
  name: redis
  labels:
    app: redis
data:
  REDIS_HOST: redis.zurek
  REDIS_PORT: "6379"
  REDIS_TTL: "5"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: zurek
  name: pgadmin-servers
  labels:
    app: pgadmin
data:
  servers.json: |
     {
       "Servers": {
         "1": {
           "Name": "PostgreSQL DB",
           "Group": "Servers",
           "Port": 5432,
           "Username": "zurek",
           "Host": "postgres.zurek",
           "SSLMode": "prefer",
           "MaintenanceDB": "postgres"
          }
        }
      }
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: zurek
  name: pgadmin
  labels:
    app: pgadmin
data:
  PGADMIN_DEFAULT_EMAIL: admin@zurek.local
  PGADMIN_LISTEN_PORT: "5050"
---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   namespace: zurek
#   name: pgadmin
#   labels:
#     app: pgadmin
# data:
#   set_password.sh: |
#     #!/bin/bash

#     createPassword() 
#     {
      
#     }