apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zurek
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:5-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        args: ["--requirepass", "$(REDIS_PASSWORD)"]
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: REDIS_PASSWORD
        resources:
          limits:
            cpu: 125m
            memory: 2Gi
          requests:
            cpu: 62m
            memory: 1Gi
        stdin: true