apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: zurek
  name: minio
spec:
  serviceName: minio
  podManagementPolicy: Parallel
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2022-01-08T03-11-54Z
          volumeMounts:
            - name: minio
              mountPath: /data
              subPath: minio-x.x.x-data
          args:
            - server
            - /data
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: minio
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: MINIO_PASSWORD
          ports:
            - containerPort: 9000
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 1Gi
          stdin: true
      serviceAccountName: minio
      volumes:
        - name: minio
          persistentVolumeClaim:
            claimName: minio