apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zurek
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2022-01-08T03-11-54Z
          volumeMounts:
            - name: minio
              mountPath: /data
              subPath: minio-x.x.x-data
          args:
            - server
            - /data
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: minio
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: MINIO_PASSWORD
          ports:
            - containerPort: 9000
          resources:
            limits:
              cpu: 125m
              memory: 1Gi
            requests:
              cpu: 62m 
              memory: 512Mi
          stdin: true
      volumes:
        - name: minio
          persistentVolumeClaim:
            claimName: minio