apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: zurek
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: registry
      containers:
        - name: frontend
          image: frontend
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 1500m
              memory: 2Gi
            requests:
              cpu: 1000m
              memory: 1Gi
          stdin: true
      serviceAccountName: frontend
      securityContext:
        runAsUser: 1000
