apiVersion: v1
kind: Service
metadata:
  namespace: zurek
  name: postgres
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
---
# apiVersion: v1
# kind: Service
# metadata:
#   namespace: zurek
#   name: pgadmin
# spec:
#   selector:
#     app: pgadmin
#   ports:
#     - port: 5050
#   type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  namespace: zurek
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  namespace: zurek
  name: minio
spec:
  selector:
    app: minio
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  namespace: zurek
  name: backend
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: zurek
  name: frontend
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - name: node
      port: 8080
    - name: storybook
      port: 6006
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-ingress
#   namespace: zurek
# spec:
#   type: NodePort
#   ports:
#     - port: 80
#       targetPort: 8080
#       protocol: TCP
#       name: http
#     - port: 443
#       targetPort: 443
#       protocol: TCP
#       name: https
#   selector:
#     app: nginx-ingress
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-ingress
#   namespace: zurek
# spec:
#   externalTrafficPolicy: Local
#   type: LoadBalancer
#   ports:
#     - port: 80
#       targetPort: 80
#       protocol: TCP
#       name: http
#     - port: 443
#       targetPort: 443
#       protocol: TCP
#       name: https
#   selector:
#     app: nginx-ingress
