apiVersion: v1
kind: Service
metadata:
  namespace: zurek
  name: postgres
spec:
  selector:
    app: postgres 
  type: NodePort
  ports:
    - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  namespace: zurek
  name: pgadmin
spec:
  selector:
    app: pgadmin 
  ports:
    - port: 5050
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  namespace: zurek
  name: redis
spec:
  selector:
    app: redis 
  ports:
    - port: 6379
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  namespace: zurek
  name: minio
spec:
  selector:
    app: minio 
  type: NodePort
  ports:
    - port: 9000
---
apiVersion: v1
kind: Service
metadata:
  namespace: zurek
  name: backend
spec:
  selector:
    app: backend 
  type: NodePort
  ports:
    - port: 3000