apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: zurek
  name: backend
  labels:
    app: backend
automountServiceAccountToken: true
secrets:
  - name: backend
  - name: postgres
  - name: backend
  - name: redis
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: zurek
  name: pgadmin
  labels:
    app: pgadmin
automountServiceAccountToken: true
secrets:
  - name: postgres
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: zurek
  name: postgres
  labels:
    app: postgres
automountServiceAccountToken: true
secrets:
  - name: postgres
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: zurek
  name: redis
  labels:
    app: redis
automountServiceAccountToken: true
secrets:
  - name: redis
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: zurek
  name: minio
  labels:
    app: minio
automountServiceAccountToken: true
secrets:
  - name: minio